### ISSUE TITLE
Concurrency-safe shared didomi instance

### ISSUE THREAD

**Issue by Carrione** [didomi/didomi-ios-sdk-spm#10]
Please make the shared didomy instance concurrency-safe

<img width="865" alt="image" src="https://github.com/user-attachments/assets/87cf2a5d-e8de-49e3-92f3-65ae9ba47a51">

**Comment by felipe-saez** [comment]
Hello,

Thank you for bringing this to our attention. We'll look into it and get back to you once it’s been addressed.

Best regards,

Felipe

**Comment by felipe-saez** [comment]
Hello,

Could you please check if you still get this warning with version 2.15.1 or later?

Kind regards,

Felipe

**Comment by felipe-saez** [comment]
Hi @Carrione,

Since we haven't heard back from you, we will be closing this issue for now. If you have any updates or further questions on this topic, please don't hesitate to reach out.

Best regards,

Felipe

**Comment by Carrione** [comment]
Hi @felipe-saez and sorry for my late response. Thank you. The warning is gone.
