### ISSUE TITLE
Error checksum

### ISSUE THREAD

**Issue by martres** [didomi/didomi-ios-sdk-spm#2]
Hello I got this error on the latest release 1.90.0

checksum of downloaded artifact of binary target 'Didomi' (98a311e4e9851874fbadb7bd46da6b35acff016fdba8803e5a8b8a5d6d80de2c) does not match checksum specified by the manifest (dfe0e8d769bee2e9931960775a3ce88218f41ad7f0f83562893e0ad86b64d398)

**Comment by JuLink** [comment]
Same here. We are on the 1.90.0 version for 1 week now but this morning we started to get this error as well.

**Comment by cyrillelegrand** [comment]
We've got the same issue here on a commercial project for one of our clients.

**Comment by geraldvoit** [comment]
Same here. 1.89.1 works.

**Comment by jawadst** [comment]
Thanks for reporting @martres @JuLink @cyrillelegrand @geraldvoit 
We have identified the issue and are working on fixing it. I'll update here when it's done.

**Comment by jawadst** [comment]
@martres @JuLink @cyrillelegrand @geraldvoit
We have fixed the issue. Do you mind testing again and confirming that it works as expected for you now?

**Comment by geraldvoit** [comment]
@jawadst Yes, my project is building with 1.90.0 without checksum error and Didomi is up and running. Thank you for the quick fix.

**Comment by JuLink** [comment]
@jawadst All good now 👍🏻

**Comment by jawadst** [comment]
Great news, thanks again for reporting the issue!

cc @felipe-saez

**Comment by martres** [comment]
@jawadst thank you very much :)
