### ISSUE TITLE
Xcode 15

### ISSUE THREAD

**Issue by brvaillant-clgx** [didomi/didomi-ios-sdk-spm#3]
Failed to build module 'Didomi'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)', while this compiler is 'Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)'). Please select a toolchain which matches the SDK

When using cocoapods version

**Comment by brvaillant-corelogic** [comment]
When using cocoa pods version

**Comment by brvaillant-clgx** [comment]
Corrected with version 1.92.0
