### ISSUE TITLE
Add Privacy Manifest

### ISSUE THREAD

**Issue by aiKrice** [didomi/didomi-ios-sdk-spm#4]
By end of spring 2024, all SDK will have to implement a Privacy manifest:
https://developer.apple.com/support/third-party-SDK-requirements/

**Comment by felipe-saez** [comment]
Hello Christopher,

Thanks for contacting us.

We are aware of these new requirements and we are currently working on them.

We'll provide an update on this issue once the required changes are released.

Kind regards,

Felipe

**Comment by emilien-io** [comment]
hi @felipe-saez, 
any update on this ?

thanks in advance

regards,

emilien

**Comment by felipe-saez** [comment]
Hello Christopher,

Version 2.3.0 of the Didomi iOS SDK has just been released. This version contains the signed XCFramework and the Privacy manifest file.

Kind regards,

Felipe

**Comment by felipe-saez** [comment]
Hello Emilien,

Version 2.3.0 of the Didomi iOS SDK has just been released. This version
contains the signed XCFramework and the Privacy manifest file.

Kind regards,

Felipe
