### ISSUE TITLE
visionOS support ?

### ISSUE THREAD

**Issue by baptistedajon** [didomi/didomi-ios-sdk-spm#5]
When I'm trying to build an visionOS with Didomi, I have this error : 
"While building for visionOS Simulator, no library for this platform was found in '~/Library/Developer/Xcode/DerivedData/Decathlon-dvhtasbzkrewxabiwmjzgfhodxnm/SourcePackages/artifacts/didomi-ios-sdk-spm/Didomi/Didomi.xcframework'.

Is it possible to add visionOS support ?
Thanks

**Comment by felipe-saez** [comment]
Hello Baptiste,

Thank you for reaching out to us with your query regarding visionOS support.

At this moment, we haven't developed support for visionOS.

We appreciate you bringing this to our attention. I have forwarded your request to our product team, and we will keep you updated on any plans to support this OS.

Best regards,

Felipe

**Comment by felipe-saez** [comment]
Hello Baptiste,

Could you please try versions 2.9.0 or 2.9.1 and see if you are able to build your app?

Best regards,

Felipe

**Comment by felipe-saez** [comment]
Hi @baptistedajon,

Since we haven't heard back from you, we will be closing this issue for now. If you have any updates or further questions on this topic, please don't hesitate to reach out.

Thank you for your understanding and cooperation.

Best regards,

Felipe
