### ISSUE TITLE
The repository could not be found

### ISSUE THREAD

**Issue by niji-mathieu-viel** [didomi/didomi-ios-sdk-spm#6]
Hello.

When following the guide to get the SDK via SPM on a brand new project, we can't get the proper framework.
Didomi is shown in the package dependancies, but it's "empty".

When checking the console for logs, the only log I could find says "The repository could not be found".

Any idea?

<img width="247" alt="Capture d’écran 2024-06-03 à 16 52 13" src="https://github.com/didomi/didomi-ios-sdk-spm/assets/60605457/f0fc61b0-075c-4c20-a6da-6bdb264bcd91">

**Comment by felipe-saez** [comment]
Hello niji-mathieu-viel,

What does it look like when you go to the "Package Dependencies" tab?

It should look something like this:
![image](https://github.com/didomi/didomi-ios-sdk-spm/assets/15191025/69440790-38a3-4967-8741-85edad1e8e9d)

Also, I would suggest cleaning the DerivedData folder and adding the package again and see if that fixes the issue.

Best regards,

Felipe

**Comment by niji-mathieu-viel** [comment]
I have this, but apparently the checkout process is not working as intended.

I found another log with this message : "Resolve Package Graph
[11:04:48]: ▸ /Users/mathieu.viel/Library/Developer/Xcode/DerivedData/PROJECT-bobzruqmxvirlqbzjhynofbxgnxm/SourcePackages/repositories/didomi-ios-sdk-spm-bf1f0076 is not valid git repository for 'https://github.com/didomi/didomi-ios-sdk-spm.git', will fetch again."

I removed my derived data several times already, still the same.

**Comment by niji-mathieu-viel** [comment]
Were you able to reproduce it? I tried on different Macs, on different networks, with or without security softwares, I always end up with Didomi via SPM without the xcframework in it (on M1 Pros)

**Comment by felipe-saez** [comment]
I wasn't able to reproduce the issue on my side. Are you able to consume other SPM dependencies?

**Comment by niji-mathieu-viel** [comment]
Yes other SPM dependencies are working correctly :( even those with zip + checksum (like firebase)

**Comment by felipe-saez** [comment]
I've created the project I'm attaching using our SPM library. It builds on my end, could you please try to see if it builds on yours?

It won't show anything because it's not properly configured but it can display your notice if you update the `AppDelegate` file using your `API Key` and `notice ID` (if you already have one configured through the Didomi Console).

```
let parameters = DidomiInitializeParameters(
            apiKey: "<YOUR API KEY>",
            noticeID: "<YOUR notice ID>"
        )
```

[DidomiTestSPM.zip](https://github.com/user-attachments/files/15759133/DidomiTestSPM.zip)

**Comment by niji-mathieu-viel** [comment]
Mmmhh ok i have a weird behavior sometimes :
<img width="1840" alt="Capture d’écran 2024-06-10 à 10 36 17" src="https://github.com/didomi/didomi-ios-sdk-spm/assets/60605457/0f2dcbf5-6de7-456a-bc7e-dcc450b71c37">

But if I retry it can work ...

I thought that the xcframework would show in the package dependancies (like other dependencies) but it's not with your current package setup, right? So basically this is an SDK we have to link in the target, not an SDK we can fully integrate in a separate module or something.

**Comment by niji-mathieu-viel** [comment]
So I guess I can close this issue :) thanks for clarifications!
