### ISSUE TITLE
Can't install 2.9.1 release with pods

### ISSUE THREAD

**Issue by hamzasoua** [didomi/didomi-ios-sdk-spm#7]
Hello,

We can't install last release with pods, the can only install 1.64.0 version

**Comment by felipe-saez** [comment]
Hello Hamza,

Thanks for your message. Could you please indicate what error you are getting?

Regards,

Felipe

**Comment by hamzasoua** [comment]
Hello Felipe,

this is my Pod:
pod 'Didomi-XCFramework', '2.9.1'

and the error:
[!] CocoaPods could not find compatible versions for pod "Didomi-XCFramework":
  In Podfile:
    Didomi-XCFramework (= 2.9.1)

**Comment by felipe-saez** [comment]
Did you try `pod install --repo-update`?

**Comment by hamzasoua** [comment]
Thank you, it work

**Comment by felipe-saez** [comment]
no problem, I'm glad that worked.

**Comment by hamzasoua** [comment]
resolved
