### ISSUE TITLE
How can I get custom vendor status?

### ISSUE THREAD

**Issue by santiagoperezALTEN** [didomi/didomi-ios-sdk-spm#8]
Hi, I was in version 'Didomi-XCFramework', '1.99.0' and currently I updated to version 'Didomi-XCFramework', '2.11.0'

I have a custom vendor ID c:airship-XXXXX, before with 1.99.0 i was able to get status value from this custom vendor ID but with the new version i can´t because of the new method:

Old: [[Didomi.shared getUserStatus].vendors.global.enabled containsObject:@"c:airship-XXXXX"]) 

New:  [Didomi.shared getCurrentUserStatus].vendors[@"c:airship-XXXXX"];

**Comment by felipe-saez** [comment]
Hello Santiago,

Could you please try by removing the `c:` prefix, i.e.: `[Didomi.shared getCurrentUserStatus].vendors[@"airship-XXXXX"];`

Best regards,

Felipe

**Comment by felipe-saez** [comment]
Hi Santiago,

Since we haven't heard back from you, we will be closing this issue for now. If you have any updates or further questions on this topic, please don't hesitate to reach out.

Best regards,

Felipe
